{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNEBlDi5QIDhk04dl8pGfHy",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/brightmain/AI-Project/blob/main/PraktekStreamlit.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "FVxGs8cr8tf7",
        "outputId": "cf5bd5b0-2688-412b-cf14-340cd6aa6caf"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2026-05-04 03:14:07.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.668 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.679 No runtime found, using MemoryCacheStorageManager\n",
            "2026-05-04 03:14:07.681 No runtime found, using MemoryCacheStorageManager\n",
            "2026-05-04 03:14:07.685 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.695 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.715 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.725 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.730 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.733 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.735 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.755 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.761 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.763 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.764 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.765 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.765 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.777 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.784 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.793 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.796 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.799 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.808 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.809 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:07.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:08.925 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:08.969 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:08.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:08.975 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:08.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:08.985 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:08.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:08.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:08.992 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.288 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:09.295 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.302 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.303 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.313 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.525 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:09.536 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.544 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.560 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.566 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.570 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.699 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:09.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.717 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.953 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:09.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.962 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.981 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:09.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.116 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:10.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.134 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.137 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.251 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:10.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.263 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.283 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.290 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.293 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.420 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:10.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.428 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "/tmp/ipykernel_4254/3183621862.py:162: FutureWarning:\n",
            "\n",
            "The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.\n",
            "\n",
            "2026-05-04 03:14:10.604 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:10.610 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.615 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.615 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.632 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:10.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.408 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:14.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.435 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.451 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.474 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:14.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.620 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.627 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.634 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.637 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.774 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:14.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.777 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.935 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:14.949 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.978 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.987 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:14.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.015 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.049 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:15.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.068 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.111 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2026-05-04 03:14:15.135 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.146 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.150 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.155 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.168 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2026-05-04 03:14:15.184 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "DeltaGenerator()"
            ]
          },
          "metadata": {},
          "execution_count": 7
        }
      ],
      "source": [
        "\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import plotly.express as px\n",
        "import plotly.graph_objects as go\n",
        "from io import StringIO\n",
        "\n",
        "# Konfigurasi halaman\n",
        "st.set_page_config(page_title=\"Mall Customers Dashboard\", layout=\"wide\")\n",
        "\n",
        "# Judul\n",
        "st.title(\"🛍️ Mall Customers Data Visualization\")\n",
        "st.markdown(\"Analisis pelanggan mall berdasarkan usia, pendapatan, dan skor belanja.\")\n",
        "\n",
        "# Load data\n",
        "@st.cache_data\n",
        "def load_data():\n",
        "    # Untuk penggunaan sebenarnya, gunakan pd.read_csv('Mall_Customers.csv')\n",
        "    # Sementara kita buat dari file yang diberikan\n",
        "    from io import StringIO\n",
        "    data_str = \"\"\"CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)\n",
        "1,Male,19,15,39\n",
        "2,Male,21,15,81\n",
        "3,Female,20,16,6\n",
        "4,Female,23,16,77\n",
        "...200,Male,30,137,83\"\"\"\n",
        "    # Use the provided string data as a fallback or for demonstration\n",
        "    df = pd.read_csv(StringIO(data_str))\n",
        "    return df\n",
        "\n",
        "df = load_data()\n",
        "\n",
        "# Sidebar filter\n",
        "st.sidebar.header(\"🔍 Filter Data\")\n",
        "gender_filter = st.sidebar.multiselect(\n",
        "    \"Pilih Gender\",\n",
        "    options=df['Gender'].unique(),\n",
        "    default=df['Gender'].unique()\n",
        ")\n",
        "age_range = st.sidebar.slider(\n",
        "    \"Rentang Usia\",\n",
        "    min_value=int(df['Age'].min()),\n",
        "    max_value=int(df['Age'].max()),\n",
        "    value=(int(df['Age'].min()), int(df['Age'].max()))\n",
        ")\n",
        "income_range = st.sidebar.slider(\n",
        "    \"Rentang Pendapatan Tahunan (k$)\",\n",
        "    min_value=int(df['Annual Income (k$)'].min()),\n",
        "    max_value=int(df['Annual Income (k$)'].max()),\n",
        "    value=(int(df['Annual Income (k$)'].min()), int(df['Annual Income (k$)'].max()))\n",
        ")\n",
        "\n",
        "# Filter data\n",
        "df_filtered = df[\n",
        "    (df['Gender'].isin(gender_filter)) &\n",
        "    (df['Age'].between(age_range[0], age_range[1])) &\n",
        "    (df['Annual Income (k$)'].between(income_range[0], income_range[1]))\n",
        "]\n",
        "\n",
        "# Metrics\n",
        "col1, col2, col3, col4 = st.columns(4)\n",
        "with col1:\n",
        "    st.metric(\"Total Customers\", len(df_filtered))\n",
        "with col2:\n",
        "    st.metric(\"Rata-rata Usia\", round(df_filtered['Age'].mean(), 1))\n",
        "with col3:\n",
        "    st.metric(\"Rata-rata Pendapatan (k$)\", round(df_filtered['Annual Income (k$)'].mean(), 1))\n",
        "with col4:\n",
        "    st.metric(\"Rata-rata Spending Score\", round(df_filtered['Spending Score (1-100)'].mean(), 1))\n",
        "\n",
        "# Tabs untuk berbagai visualisasi\n",
        "tab1, tab2, tab3, tab4, tab5 = st.tabs([\n",
        "    \"📊 Distribusi Data\",\n",
        "    \"👥 Analisis Gender\",\n",
        "    \"💰 Pendapatan vs Spending\",\n",
        "    \"🎯 Segmentasi Pelanggan\",\n",
        "    \"📈 Tren Usia\"\n",
        "])\n",
        "\n",
        "with tab1:\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        st.subheader(\"Distribusi Usia\")\n",
        "        fig1 = px.histogram(df_filtered, x='Age', nbins=20, color='Gender',\n",
        "                            title='Distribusi Usia Berdasarkan Gender',\n",
        "                            labels={'Age': 'Usia', 'count': 'Jumlah'})\n",
        "        st.plotly_chart(fig1, use_container_width=True)\n",
        "\n",
        "    with col2:\n",
        "        st.subheader(\"Distribusi Spending Score\")\n",
        "        fig2 = px.histogram(df_filtered, x='Spending Score (1-100)', nbins=20, color='Gender',\n",
        "                            title='Distribusi Spending Score',\n",
        "                            labels={'Spending Score (1-100)': 'Spending Score'})\n",
        "        st.plotly_chart(fig2, use_container_width=True)\n",
        "\n",
        "    st.subheader(\"Distribusi Pendapatan Tahunan\")\n",
        "    fig3 = px.box(df_filtered, x='Gender', y='Annual Income (k$)',\n",
        "                  title='Boxplot Pendapatan per Gender',\n",
        "                  color='Gender')\n",
        "    st.plotly_chart(fig3, use_container_width=True)\n",
        "\n",
        "with tab2:\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        # Perbandingan gender\n",
        "        gender_count = df_filtered['Gender'].value_counts().reset_index()\n",
        "        gender_count.columns = ['Gender', 'Count']\n",
        "        fig4 = px.pie(gender_count, values='Count', names='Gender',\n",
        "                      title='Proporsi Gender', hole=0.3)\n",
        "        st.plotly_chart(fig4, use_container_width=True)\n",
        "\n",
        "    with col2:\n",
        "        # Rata-rata per gender\n",
        "        gender_stats = df_filtered.groupby('Gender').agg({\n",
        "            'Age': 'mean',\n",
        "            'Annual Income (k$)': 'mean',\n",
        "            'Spending Score (1-100)': 'mean'\n",
        "        }).reset_index()\n",
        "        gender_stats_melted = gender_stats.melt(id_vars='Gender',\n",
        "                                                 value_vars=['Age', 'Annual Income (k$)', 'Spending Score (1-100)'],\n",
        "                                                 var_name='Metric', value_name='Average')\n",
        "        fig5 = px.bar(gender_stats_melted, x='Metric', y='Average', color='Gender',\n",
        "                      title='Rata-rata Metrik per Gender', barmode='group')\n",
        "        st.plotly_chart(fig5, use_container_width=True)\n",
        "\n",
        "    st.subheader(\"Spending Score per Gender berdasarkan Usia\")\n",
        "    fig6 = px.scatter(df_filtered, x='Age', y='Spending Score (1-100)',\n",
        "                      color='Gender', size='Annual Income (k$)',\n",
        "                      title='Hubungan Usia dan Spending Score',\n",
        "                      labels={'Age': 'Usia', 'Spending Score (1-100)': 'Spending Score'})\n",
        "    st.plotly_chart(fig6, use_container_width=True)\n",
        "\n",
        "with tab3:\n",
        "    st.subheader(\"Hubungan Pendapatan dan Spending Score\")\n",
        "\n",
        "    # Scatter plot interaktif\n",
        "    fig7 = px.scatter(df_filtered, x='Annual Income (k$)', y='Spending Score (1-100)',\n",
        "                      color='Gender', size='Age', hover_data=['CustomerID'],\n",
        "                      title='Annual Income vs Spending Score',\n",
        "                      labels={'Annual Income (k$)': 'Pendapatan Tahunan (k$)',\n",
        "                              'Spending Score (1-100)': 'Spending Score'})\n",
        "    st.plotly_chart(fig7, use_container_width=True)\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        # Korelasi\n",
        "        st.subheader(\"Korelasi Antar Variabel\")\n",
        "        corr_matrix = df_filtered[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']].corr()\n",
        "        fig8 = px.imshow(corr_matrix, text_auto=True, aspect=\"auto\",\n",
        "                         title=\"Heatmap Korelasi\")\n",
        "        st.plotly_chart(fig8, use_container_width=True)\n",
        "\n",
        "    with col2:\n",
        "        # Tren berdasarkan usia\n",
        "        age_groups = pd.cut(df_filtered['Age'], bins=[0, 25, 35, 45, 55, 100],\n",
        "                            labels=['18-25', '26-35', '36-45', '46-55', '56+'])\n",
        "        df_filtered['Age Group'] = age_groups\n",
        "        age_income_spending = df_filtered.groupby('Age Group')[['Annual Income (k$)', 'Spending Score (1-100)']].mean().reset_index()\n",
        "        age_income_spending_melted = age_income_spending.melt(id_vars='Age Group',\n",
        "                                                              value_vars=['Annual Income (k$)', 'Spending Score (1-100)'],\n",
        "                                                              var_name='Metric', value_name='Average')\n",
        "        fig9 = px.line(age_income_spending_melted, x='Age Group', y='Average',\n",
        "                       color='Metric', title='Rata-rata Pendapatan dan Spending per Kelompok Usia',\n",
        "                       markers=True)\n",
        "        st.plotly_chart(fig9, use_container_width=True)\n",
        "\n",
        "with tab4:\n",
        "    st.subheader(\"Segmentasi Pelanggan (Clustering Sederhana)\")\n",
        "\n",
        "    from sklearn.cluster import KMeans\n",
        "\n",
        "    # Pilih fitur untuk clustering\n",
        "    X = df_filtered[['Annual Income (k$)', 'Spending Score (1-100)']].copy()\n",
        "\n",
        "    # KMeans dengan 5 cluster\n",
        "    kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)\n",
        "    df_filtered['Cluster'] = kmeans.fit_predict(X)\n",
        "\n",
        "    # Mapping cluster ke label\n",
        "    cluster_labels = {\n",
        "        0: 'Pendapatan Rendah - Spending Rendah',\n",
        "        1: 'Pendapatan Sedang - Spending Sedang',\n",
        "        2: 'Pendapatan Tinggi - Spending Rendah',\n",
        "        3: 'Pendapatan Rendah - Spending Tinggi',\n",
        "        4: 'Pendapatan Tinggi - Spending Tinggi'\n",
        "    }\n",
        "    df_filtered['Segment'] = df_filtered['Cluster'].map(cluster_labels)\n",
        "\n",
        "    fig10 = px.scatter(df_filtered, x='Annual Income (k$)', y='Spending Score (1-100)',\n",
        "                       color='Segment', size='Age', hover_data=['Gender', 'Age'],\n",
        "                       title='Segmentasi Pelanggan (K-Means Clustering)',\n",
        "                       labels={'Annual Income (k$)': 'Pendapatan Tahunan (k$)',\n",
        "                               'Spending Score (1-100)': 'Spending Score'})\n",
        "    st.plotly_chart(fig10, use_container_width=True)\n",
        "\n",
        "    # Statistik per segment\n",
        "    st.subheader(\"Statistik per Segment\")\n",
        "    segment_stats = df_filtered.groupby('Segment').agg({\n",
        "        'CustomerID': 'count',\n",
        "        'Age': 'mean',\n",
        "        'Annual Income (k$)': 'mean',\n",
        "        'Spending Score (1-100)': 'mean'\n",
        "    }).round(1)\n",
        "    segment_stats.columns = ['Jumlah', 'Rata-rata Usia', 'Rata-rata Pendapatan', 'Rata-rata Spending']\n",
        "    st.dataframe(segment_stats, use_container_width=True)\n",
        "\n",
        "with tab5:\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        st.subheader(\"Spending Score Berdasarkan Usia\")\n",
        "        fig11 = px.line(df_filtered.groupby('Age')['Spending Score (1-100)'].mean().reset_index(),\n",
        "                        x='Age', y='Spending Score (1-100)',\n",
        "                        title='Tren Spending Score Berdasarkan Usia',\n",
        "                        markers=True)\n",
        "        st.plotly_chart(fig11, use_container_width=True)\n",
        "\n",
        "    with col2:\n",
        "        st.subheader(\"Pendapatan Berdasarkan Usia\")\n",
        "        fig12 = px.line(df_filtered.groupby('Age')['Annual Income (k$)'].mean().reset_index(),\n",
        "                        x='Age', y='Annual Income (k$)',\n",
        "                        title='Tren Pendapatan Berdasarkan Usia',\n",
        "                        markers=True)\n",
        "        st.plotly_chart(fig12, use_container_width=True)\n",
        "\n",
        "    st.subheader(\"Top 20 Customer dengan Spending Score Tertinggi\")\n",
        "    top_customers = df_filtered.nlargest(20, 'Spending Score (1-100)')[['CustomerID', 'Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)']]\n",
        "    st.dataframe(top_customers, use_container_width=True)\n",
        "\n",
        "# Tampilkan data mentah\n",
        "with st.expander(\"📋 Lihat Data Mentah\"):\n",
        "    st.dataframe(df_filtered, use_container_width=True)\n",
        "\n",
        "# Footer\n",
        "st.markdown(\"---\")\n",
        "st.markdown(\"Dashboard ini dibuat untuk analisis data pelanggan mall.\")"
      ]
    }
  ]
}